name: eichwalde_app
description: "Eichwalde App."
publish_to: 'none' 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.

version: 1.0.0+2002

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. 
dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.20.1
  # flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  flutter_timezone: ^4.0.0
  numberpicker: ^2.1.2
  table_calendar: ^3.2.0
  cron: ^0.6.1
  expandable: ^5.0.1
  shared_preferences: ^2.5.2
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  flutter_launcher_icons: ^0.14.3
  flutter_pdfview: ^1.4.0
  flutter_cached_pdfview: ^0.4.3
  url_launcher: ^6.3.1
  maps_launcher: ^3.0.0+1
  home_widget: ^0.7.0+1
  gradient_borders: ^1.0.1

dependency_overrides:
  shared_preferences_android: 2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "Assets/IconEichwalde.png"
  adaptive_icon_background: "Assets/IconEichwalde.png"
  adaptive_icon_foreground: "Assets/IconEichwalde.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - Assets/S46.png
    - Assets/Bus.png
    - Assets/S8.png
    - Assets/wappen_Eichwalde.png
    - Assets/image2.png
    - Assets/image3.png
    - Assets/image4.png
    - Assets/image5.png
    - Assets/image6.png
    - Assets/image7.png
    - Assets/image8.png
    - Assets/image9.png
    - Assets/image10.png
    - Assets/image11.png
    - Assets/image12.png
    - Assets/image13.png
    - Assets/image14.png
    - Assets/image15.png
    - Assets/image16.png
    - Assets/image17.png
    - Assets/Facebook_icon.png
    - Assets/Instagram_icon.png
    - Assets/Youtube_icon.png
    - Assets/IconEichwalde.png
    - Assets/IconEichwaldeneu2.png
    
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
